version: 1
update_configs:
  - package_manager: "python"
    directory: "ebr_board"
    update_schedule: "live"
    commit_message:
      prefix: "fix"
      prefix_development: "chore"
      include_scope: true
    default_reviewers:
      - "eugene-davis"
      - "bestdeveloperever"
